:PROPERTIES:
:ID:       c32530ad-a9fb-49e9-a32a-3fb6cd7a56d2
:END:
#+title: Lymphatic System 
#+filetags: :system:

How can immune cells meet and provide the necessary stimulation efficiently when they must first be activated?
How is this done quickly enough such that invaders are eliminated?
This is the (main) purpose of the lymphatic system.

* Structure
** Adenoids

** Appendix

** Bone Marrow

** Bronchus-associated Lymphoid Tissue

** Intestine

** Lymph Nodes
:PROPERTIES:
:ID:       e4224d01-d723-4ebf-af3a-d9d5f708abf6
:END:
There are hundreds of lymph nodes throughout the body.
They act as outposts where immune cells can meet and interact, giving each other the activating and costimulatory signals necessary to launch a successful immune response.

The node is surrounded by a protective layer of connective tissue: the capsule.
Lymph arrives at the node by afferent lymphatic vessels, then entering into the sinuses, channels that allow lymph to flow through the different compartments of the node.

These sinuses are lined with [[id:96a95dcb-e977-4788-8c70-8e110e6cde04][macrophages]] and [[id:0c0acdcc-f093-41d2-a7b8-0db4a99478ad][dendritic cells]].
These sample the lymph for pathogens and cellular debris. If they catch pathogens or debris that can trigger an immune reaction, they present those antigens to [[id:b41a8603-b190-47ff-b727-e8aee492818c][T cells]].
The [[id:96a95dcb-e977-4788-8c70-8e110e6cde04][macrophages]] act as filters in the node, trapping lymph-borne pathogens and preventing them from infecting other cells in the node and beyond.

Each node has specific compartments for distinct cell types. This is largely defined by [[id:ca6eb72d-0192-41ad-9ca4-d6ad5aae6d63][chemokines]]. These allow for [[id:49c29c2a-80c4-4e8b-9ab3-6c4e12129e1c][lymphocytes]] to efficiently find their [[id:7f1f4f7c-d8dd-47bc-9bb9-17e1513a634c][cognate antigens]] and interact with other cells in order to initiate an immune response.
Closer to the capsule is the outer cortex, also known as the [[id:59e57bc1-545d-4cdb-9d15-3318fffeaa08][B cell]] zone. It is made up of spherical follicles full of [[id:59e57bc1-545d-4cdb-9d15-3318fffeaa08][B cells]]. Deeper into the node is the [[id:b41a8603-b190-47ff-b727-e8aee492818c][T cell]] zone.

[[id:0c0acdcc-f093-41d2-a7b8-0db4a99478ad][DC]]s that have been sampling bits of microbes or cellular debris throughout the body migrate to the T cell zone of lymph nodes after activation. Then, they present these antigens to the [[id:b41a8603-b190-47ff-b727-e8aee492818c][T cells]], looking for the one that matches their [[id:262f459e-3873-4ce0-819f-03eab3300722][antigen]].
[[id:f68ee1e7-75a1-449d-8e39-38b88e0d82af][Helper T cells]] tend to live in the margins between T and B cell zones, allowing them to find the [[id:59e57bc1-545d-4cdb-9d15-3318fffeaa08][B cell]] that shares its [[id:7f1f4f7c-d8dd-47bc-9bb9-17e1513a634c][cognate antigen]]. This gives rise to *germinal centers*, sites of [[id:59e57bc1-545d-4cdb-9d15-3318fffeaa08][B cell]] activation and division.

[[id:e4f76ad7-2a12-4edf-bd0a-f2c4e44cc81e][Naïve lymphocytes]] drain from the blood into the lymph nodes, where they circulate through their respective zones, looking for cells presenting their [[id:7f1f4f7c-d8dd-47bc-9bb9-17e1513a634c][cognate antigen]].
If they don't find it, they move from node to node and then back into the bloodstream.
If they do and receive the proper costimulation, the [[id:49c29c2a-80c4-4e8b-9ab3-6c4e12129e1c][lymphocyte]] becomes activated. It starts dividing rapidly and then migrates to the infection site.

** Payer's Patches

** Spleen
:PROPERTIES:
:ID:       fb07ddef-6a28-40c5-be6e-5a567e35d221
:END:
The largest lymphatic organ in the body.
It's dark-red, sitting right behind the stomach.
It has two main functions. It removes old [[id:d9373e6f-2194-4a5a-b1f9-6e492dea23c7][red blood cells]] from circulation, in the red pulp, and it filters out pathogens and immune complexes from the blood, in the white pulp.
However, unlike the Lymph Nodes, it only filters blood, not lymph.
Additionally, the spleen holds an emergency reserve of blood, platelets, and [[id:d0543e0a-ef0b-4990-b67b-c68084aa2467][monocytes]].

The Red Pulp makes up around 75% of the spleen's volume and is comprised of the Cords of Billroth and venous sinus.
The Cords of Billroth, also known as the splenic cords, are lined with connective tissue and fibroblasts. They are also full of [[id:96a95dcb-e977-4788-8c70-8e110e6cde04][macrophages]].
Splenic blood enters open circulation in the cords, i.e., it doesn't flow through endothelial-lined vessels, and here old or damaged [[id:d9373e6f-2194-4a5a-b1f9-6e492dea23c7][RBC]]s can be [[id:50e80900-a8db-4435-b457-12ea355843d9][phagocytized]].
In order to re-enter circulation, [[id:d9373e6f-2194-4a5a-b1f9-6e492dea23c7][RBC]]s must enter the venous sinuses by passing through the interendothelial slit.

** Thymus

** Tonsils


* Function
Many Lymphatic Capillaries are spread throughout tissues.
These receive fluids, proteins and potential pathogens.
This fluid, called Lymph, is pushed through Lymphatic Vessels into the Lymph Nodes.
